### ISSUE TITLE
Touch ID/Face ID + autofill password POC

### ISSUE THREAD

**Issue by marinofelipe** [marinofelipe/personal_todo_management#25]
POC -> biometric access

Password autofill - when user is not using 
Touch ID/ Face ID

### Tasks
- [x] [WWDC 17 - Introducing password autofill for apps](https://developer.apple.com/videos/play/wwdc2017/206)
- [x] [WWDC 18 - Automatic Strong Passwords and Security Code AutoFill](https://developer.apple.com/videos/play/wwdc2018/204/)
- [x] [WWDC 14 - Keychain and Authentication with Touch ID](https://developer.apple.com/videos/play/wwdc2014/711/)
- [x] Create repo + project
- [x] Password Autofill
