### ISSUE TITLE
research iOS test coverage tools. Take a look more deeply in UITests.

### ISSUE THREAD

**Issue by marinofelipe** [marinofelipe/personal_todo_management#7]
related to [guild-apps task](https://github.com/GrupoZapVivaReal/guild-apps/issues/2)

# Tasks
- [ ] [Try browserStack] https://www.browserstack.com/app-automate
- [ ] Search other tools
- [ ] Search the availability of normal XCUITests and slather with coverage
- [ ] Take a look at free alternatives for Coveralls
- [ ] List other tools to study here..

**Comment by marinofelipe** [comment]
### Output

- Slather barely support UI testing. So UI coverage report is not expected through slather.
- Besides that, UI tests generally are not related to the project code itself, but to verify if the UI respect specified layout.
